// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package models

import (
	"time"
)

// CHAR defines model for CHAR.
type CHAR = string

// DATE defines model for DATE.
type DATE = time.Time

// NUMBER defines model for NUMBER.
type NUMBER = float32

// VARCHAR2 defines model for VARCHAR2.
type VARCHAR2 = string

// GetAdresseParams defines parameters for GetAdresse.
type GetAdresseParams struct {
	// AdresseNr Implicit parameter
	AdresseNr *string `form:"adresse_nr,omitempty" json:"adresse_nr,omitempty"`
}

// GetAntragParams defines parameters for GetAntrag.
type GetAntragParams struct {
	// Antragnr Implicit parameter
	Antragnr *string `form:"antragnr,omitempty" json:"antragnr,omitempty"`

	// AntragstellerNr Implicit parameter
	AntragstellerNr *string `form:"antragsteller_nr,omitempty" json:"antragsteller_nr,omitempty"`

	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetAuflageReduParams defines parameters for GetAuflageRedu.
type GetAuflageReduParams struct {
	// Auflagenr Implicit parameter
	Auflagenr *string `form:"auflagenr,omitempty" json:"auflagenr,omitempty"`
}

// GetAuflagenParams defines parameters for GetAuflagen.
type GetAuflagenParams struct {
	// Auflage Implicit parameter
	Auflage *string `form:"auflage,omitempty" json:"auflage,omitempty"`

	// Auflagenr Implicit parameter
	Auflagenr *string `form:"auflagenr,omitempty" json:"auflagenr,omitempty"`

	// Ebene Implicit parameter
	Ebene *string `form:"ebene,omitempty" json:"ebene,omitempty"`
}

// GetAwgParams defines parameters for GetAwg.
type GetAwgParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`

	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetAwgAufwandParams defines parameters for GetAwgAufwand.
type GetAwgAufwandParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgBemParams defines parameters for GetAwgBem.
type GetAwgBemParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgKulturParams defines parameters for GetAwgKultur.
type GetAwgKulturParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgPartnerParams defines parameters for GetAwgPartner.
type GetAwgPartnerParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgPartnerAufwandParams defines parameters for GetAwgPartnerAufwand.
type GetAwgPartnerAufwandParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgSchadorgParams defines parameters for GetAwgSchadorg.
type GetAwgSchadorgParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgVerwendungszweckParams defines parameters for GetAwgVerwendungszweck.
type GetAwgVerwendungszweckParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgWartezeitParams defines parameters for GetAwgWartezeit.
type GetAwgWartezeitParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`

	// AwgWartezeitNr Implicit parameter
	AwgWartezeitNr *string `form:"awg_wartezeit_nr,omitempty" json:"awg_wartezeit_nr,omitempty"`

	// Kultur Implicit parameter
	Kultur *string `form:"kultur,omitempty" json:"kultur,omitempty"`
}

// GetAwgWartezeitAusgKulturParams defines parameters for GetAwgWartezeitAusgKultur.
type GetAwgWartezeitAusgKulturParams struct {
	// AwgWartezeitNr Implicit parameter
	AwgWartezeitNr *string `form:"awg_wartezeit_nr,omitempty" json:"awg_wartezeit_nr,omitempty"`

	// Kultur Implicit parameter
	Kultur *string `form:"kultur,omitempty" json:"kultur,omitempty"`
}

// GetAwgZeitpunktParams defines parameters for GetAwgZeitpunkt.
type GetAwgZeitpunktParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetAwgZulassungParams defines parameters for GetAwgZulassung.
type GetAwgZulassungParams struct {
	// AwgId Implicit parameter
	AwgId *string `form:"awg_id,omitempty" json:"awg_id,omitempty"`
}

// GetGhsGefahrenhinweiseParams defines parameters for GetGhsGefahrenhinweise.
type GetGhsGefahrenhinweiseParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetGhsGefahrensymboleParams defines parameters for GetGhsGefahrensymbole.
type GetGhsGefahrensymboleParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetGhsSicherheitshinweiseParams defines parameters for GetGhsSicherheitshinweise.
type GetGhsSicherheitshinweiseParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetGhsSignalwoerterParams defines parameters for GetGhsSignalwoerter.
type GetGhsSignalwoerterParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetHinweisParams defines parameters for GetHinweis.
type GetHinweisParams struct {
	// Ebene Implicit parameter
	Ebene *string `form:"ebene,omitempty" json:"ebene,omitempty"`
}

// GetKodeParams defines parameters for GetKode.
type GetKodeParams struct {
	// Kode Implicit parameter
	Kode *string `form:"kode,omitempty" json:"kode,omitempty"`

	// Kodeliste Implicit parameter
	Kodeliste *string `form:"kodeliste,omitempty" json:"kodeliste,omitempty"`

	// Sprache Implicit parameter
	Sprache *string `form:"sprache,omitempty" json:"sprache,omitempty"`
}

// GetKodelisteParams defines parameters for GetKodeliste.
type GetKodelisteParams struct {
	// Kodeliste Implicit parameter
	Kodeliste *string `form:"kodeliste,omitempty" json:"kodeliste,omitempty"`
}

// GetKodelisteFeldnameParams defines parameters for GetKodelisteFeldname.
type GetKodelisteFeldnameParams struct {
	// Feldname Implicit parameter
	Feldname *string `form:"feldname,omitempty" json:"feldname,omitempty"`

	// Kodeliste Implicit parameter
	Kodeliste *string `form:"kodeliste,omitempty" json:"kodeliste,omitempty"`

	// Tabelle Implicit parameter
	Tabelle *string `form:"tabelle,omitempty" json:"tabelle,omitempty"`
}

// GetKulturGruppeParams defines parameters for GetKulturGruppe.
type GetKulturGruppeParams struct {
	// Kultur Implicit parameter
	Kultur *string `form:"kultur,omitempty" json:"kultur,omitempty"`

	// KulturGruppe Implicit parameter
	KulturGruppe *string `form:"kultur_gruppe,omitempty" json:"kultur_gruppe,omitempty"`
}

// GetMittelParams defines parameters for GetMittel.
type GetMittelParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetMittelAbgelaufenParams defines parameters for GetMittelAbgelaufen.
type GetMittelAbgelaufenParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetMittelAbpackungParams defines parameters for GetMittelAbpackung.
type GetMittelAbpackungParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetMittelGefahrenSymbolParams defines parameters for GetMittelGefahrenSymbol.
type GetMittelGefahrenSymbolParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetMittelVertriebParams defines parameters for GetMittelVertrieb.
type GetMittelVertriebParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`

	// VertriebsfirmaNr Implicit parameter
	VertriebsfirmaNr *string `form:"vertriebsfirma_nr,omitempty" json:"vertriebsfirma_nr,omitempty"`
}

// GetMittelWirkbereichParams defines parameters for GetMittelWirkbereich.
type GetMittelWirkbereichParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`

	// Wirkungsbereich Implicit parameter
	Wirkungsbereich *string `form:"wirkungsbereich,omitempty" json:"wirkungsbereich,omitempty"`
}

// GetParallelimportAbgelaufenParams defines parameters for GetParallelimportAbgelaufen.
type GetParallelimportAbgelaufenParams struct {
	// ImporteurNr Implicit parameter
	ImporteurNr *string `form:"importeur_nr,omitempty" json:"importeur_nr,omitempty"`

	// PiReferenzKennr Implicit parameter
	PiReferenzKennr *string `form:"pi_referenz_kennr,omitempty" json:"pi_referenz_kennr,omitempty"`
}

// GetParallelimportGueltigParams defines parameters for GetParallelimportGueltig.
type GetParallelimportGueltigParams struct {
	// ImporteurNr Implicit parameter
	ImporteurNr *string `form:"importeur_nr,omitempty" json:"importeur_nr,omitempty"`

	// PiReferenzKennr Implicit parameter
	PiReferenzKennr *string `form:"pi_referenz_kennr,omitempty" json:"pi_referenz_kennr,omitempty"`
}

// GetSchadorgGruppeParams defines parameters for GetSchadorgGruppe.
type GetSchadorgGruppeParams struct {
	// Schadorg Implicit parameter
	Schadorg *string `form:"schadorg,omitempty" json:"schadorg,omitempty"`

	// SchadorgGruppe Implicit parameter
	SchadorgGruppe *string `form:"schadorg_gruppe,omitempty" json:"schadorg_gruppe,omitempty"`
}

// GetStaerkungParams defines parameters for GetStaerkung.
type GetStaerkungParams struct {
	// AntragstellerNr Implicit parameter
	AntragstellerNr *string `form:"antragsteller_nr,omitempty" json:"antragsteller_nr,omitempty"`

	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetStaerkungVertriebParams defines parameters for GetStaerkungVertrieb.
type GetStaerkungVertriebParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`

	// VertriebsfirmaNr Implicit parameter
	VertriebsfirmaNr *string `form:"vertriebsfirma_nr,omitempty" json:"vertriebsfirma_nr,omitempty"`
}

// GetWirkstoffParams defines parameters for GetWirkstoff.
type GetWirkstoffParams struct {
	// Wirknr Implicit parameter
	Wirknr *string `form:"wirknr,omitempty" json:"wirknr,omitempty"`
}

// GetWirkstoffGehaltParams defines parameters for GetWirkstoffGehalt.
type GetWirkstoffGehaltParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`

	// Wirknr Implicit parameter
	Wirknr *string `form:"wirknr,omitempty" json:"wirknr,omitempty"`
}

// GetZusatzstoffParams defines parameters for GetZusatzstoff.
type GetZusatzstoffParams struct {
	// AntragstellerNr Implicit parameter
	AntragstellerNr *string `form:"antragsteller_nr,omitempty" json:"antragsteller_nr,omitempty"`

	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`
}

// GetZusatzstoffVertriebParams defines parameters for GetZusatzstoffVertrieb.
type GetZusatzstoffVertriebParams struct {
	// Kennr Implicit parameter
	Kennr *string `form:"kennr,omitempty" json:"kennr,omitempty"`

	// VertriebsfirmaNr Implicit parameter
	VertriebsfirmaNr *string `form:"vertriebsfirma_nr,omitempty" json:"vertriebsfirma_nr,omitempty"`
}
